In [1]:
## The following code ensures that all functions and init files are reloaded before executions.
%load_ext autoreload
%autoreload 2

In [2]:
import dask
dask.config.set({'dataframe.query-planning': False})
import spatialdata

c:\Users\ge37voy\AppData\Local\miniconda3\envs\sd313\Lib\site-packages\dask\dataframe\__init__.py:31: FutureWarning: The legacy Dask DataFrame implementation is deprecated and will be removed in a future version. Set the configuration option `dataframe.query-planning` to `True` or None to enable the new Dask Dataframe implementation and silence this warning.
  warnings.warn(
c:\Users\ge37voy\AppData\Local\miniconda3\envs\sd313\Lib\site-packages\xarray_schema\__init__.py:1: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  from pkg_resources import DistributionNotFound, get_distribution
c:\Users\ge37voy\AppData\Local\miniconda3\envs\sd313\Lib\site-packages\spatialdata\_core\query\relational_query.py:530: FutureWarning: functools.partial will be a method descriptor in future Python versions; wrap it in enum.member() if you want to preserve the old behavior
  left = partial(_left_join_spatialelement_table)
c:\Users\ge37voy\AppData\Local\miniconda3\envs\sd313\Lib\site-packages\spatialdata\_core\query\relational_query.py:531: FutureWarning: functools.partial will be a method descriptor in future Python versions; wrap it in enum.member() if you want to preserve the old behavior
  left_exclusive = partial(_left_exclusive_join_spatialelement_table)
c:\Users\ge37voy\AppData\Local\miniconda3\envs\sd313\Lib\site-packages\spatialdata\_core\query\relational_query.py:532: FutureWarning: functools.partial will be a method descriptor in future Python versions; wrap it in enum.member() if you want to preserve the old behavior
  inner = partial(_inner_join_spatialelement_table)
c:\Users\ge37voy\AppData\Local\miniconda3\envs\sd313\Lib\site-packages\spatialdata\_core\query\relational_query.py:533: FutureWarning: functools.partial will be a method descriptor in future Python versions; wrap it in enum.member() if you want to preserve the old behavior
  right = partial(_right_join_spatialelement_table)
c:\Users\ge37voy\AppData\Local\miniconda3\envs\sd313\Lib\site-packages\spatialdata\_core\query\relational_query.py:534: FutureWarning: functools.partial will be a method descriptor in future Python versions; wrap it in enum.member() if you want to preserve the old behavior
  right_exclusive = partial(_right_exclusive_join_spatialelement_table)

In [3]:
from insitupy.datasets import xenium_human_breast_cancer, visium_human_breast_cancer

c:\Users\ge37voy\AppData\Local\miniconda3\envs\sd313\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [4]:
xenium = xenium_human_breast_cancer()
xenium.load_all()

This dataset exists already. Download is skipped. To force download set `overwrite=True`.
Image exists. Checking md5sum...

INFO: Reading Xenium data with InSituPy backend...

The md5sum matches. Download is skipped. To force download set `overwrite=True`.
Image exists. Checking md5sum...
The md5sum matches. Download is skipped. To force download set `overwrite=True`.
Corresponding image data can be found in C:\Users\ge37voy\.cache\InSituPy\demo_datasets\xenium_hbreastcancer\unregistered_images
For this dataset following images are available:
slide_id__hbreastcancer__HE__histo.ome.tiff
slide_id__hbreastcancer__CD20_HER2_DAPI__IF.ome.tiff
Loading cells...
Loading images...
Loading transcripts...

In [5]:
xenium

InSituData
Method:		Xenium
Slide ID:	0001879
Sample ID:	Replicate 1
Path:		C:\Users\ge37voy\.cache\InSituPy\demo_datasets\xenium_hbreastcancer\output-XETG00000__slide_id__hbreastcancer

    ➤ images
       'nuclei':   (25778, 35416)
    ➤ cells
       MultiCellData with main layer 'main'
           matrix
               AnnData object with n_obs × n_vars = 167780 × 313
               obs: 'transcript_counts', 'control_probe_counts', 'control_codeword_counts', 'total_counts', 'cell_area', 'nucleus_area'
               var: 'gene_ids', 'feature_types', 'genome'
               obsm: 'spatial'
           boundaries
               BoundariesData object with 2 entries:
                   cells
                   nuclei
    ➤ transcripts
       DataFrame with shape Delayed('int-64ea1676-6a3e-47b7-8fbc-efe5ca883aca') x 8

In [6]:
# from insitupy.io import read_xenium
# p = r"C:\Users\ge37voy\.cache\InSituPy\demo_datasets\xenium_hbreastcancer\output-XETG00000__slide_id__hbreastcancer"
# x = read_xenium(p, backend="spatialdata")

In [9]:
visium = visium_human_breast_cancer()

INFO: Reading Visium data with spatialdata-io...

H5 file exists. Checking md5sum...
The h5 file md5sum matches. Download is skipped. To force download set `overwrite=True`.
Spatial directory exists. Download is skipped. To force download set `overwrite=True`.
Visium data structure is ready at C:\Users\ge37voy\.cache\InSituPy\demo_datasets\visium_hbreastcancer\CytAssist_FFPE_Human_Breast_Cancer
Dataset contains:
- filtered_feature_bc_matrix.h5
- spatial/ directory

c:\Users\ge37voy\AppData\Local\miniconda3\envs\sd313\Lib\site-packages\anndata\_core\anndata.py:1798: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")
c:\Users\ge37voy\AppData\Local\miniconda3\envs\sd313\Lib\site-packages\anndata\_core\anndata.py:1798: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")
c:\Users\ge37voy\AppData\Local\miniconda3\envs\sd313\Lib\site-packages\spatialdata\models\models.py:1183: UserWarning: Converting `region_key: region` to categorical dtype.
  convert_region_column_to_categorical(adata)
INFO: Using 'visium' coordinate system for pixel size extraction.

Adding images...

WARNING: Indices in `.shapes` do not match `.data.obs_names`. Shapes will be renamed according to the `obs_names`. For this to be valid, please make sure that the order of elements in `.shapes` and `.data` matches.

In [10]:
visium.images.metadata

{'hires': {'filename': None,
  'shape': (3, 2000, 1809),
  'axes': 'CYX',
  'OME': {},
  'pixel_size': 5.906139790390711,
  'rgb': False},
 'lowres': {'filename': None,
  'shape': (3, 600, 543),
  'axes': 'CYX',
  'OME': {},
  'pixel_size': 19.687132776192747,
  'rgb': False}}

In [16]:
from insitupy import CACHE, InSituData

In [15]:
visium_out = CACHE / "out/features_test"
visium.saveas(visium_out, overwrite=True)

Saving data to C:\Users\ge37voy\.cache\InSituPy\out\features_test
Saved.

In [20]:
vr = InSituData.read(visium_out)
vr.load_all()

In [21]:
vr

InSituData
Method:		Visium
Slide ID:	slide_id
Sample ID:	sample_id
Path:		C:\Users\ge37voy\.cache\InSituPy\out\features_test

    ➤ images
       'hires':    (3, 2000, 1809)
       'lowres':   (3, 600, 543)
    ➤ features
       FeatureData (Type: 'feature')
           .data: 4992 obs × 18085 vars
           .shapes: 4992 geometries

In [27]:
xenium.images.metadata['nuclei']['pixel_size']

0.2125

# What is the unit of the coordinates in a Visium dataset?

In [50]:
from spatialdata_io import visium
v = visium(r"C:\Users\ge37voy\.cache\InSituPy\demo_datasets\visium_hbreastcancer\CytAssist_FFPE_Human_Breast_Cancer",
           dataset_id="test",
           fullres_image_file=r"C:\Users\ge37voy\.cache\InSituPy\demo_datasets\visium_hbreastcancer\CytAssist_FFPE_Human_Breast_Cancer\CytAssist_FFPE_Human_Breast_Cancer_tissue_image.tif")

c:\Users\ge37voy\AppData\Local\miniconda3\envs\sd313\Lib\site-packages\anndata\_core\anndata.py:1798: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")
c:\Users\ge37voy\AppData\Local\miniconda3\envs\sd313\Lib\site-packages\anndata\_core\anndata.py:1798: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")
c:\Users\ge37voy\AppData\Local\miniconda3\envs\sd313\Lib\site-packages\spatialdata\models\models.py:1183: UserWarning: Converting `region_key: region` to categorical dtype.
  convert_region_column_to_categorical(adata)

In [52]:
v

SpatialData object
├── Images
│     ├── 'test_full_image': DataTree[cyx] (3, 21571, 19505), (3, 10785, 9752), (3, 5392, 4876), (3, 2696, 2438), (3, 1348, 1219)
│     ├── 'test_hires_image': DataArray[cyx] (3, 2000, 1809)
│     └── 'test_lowres_image': DataArray[cyx] (3, 600, 543)
├── Shapes
│     └── 'test': GeoDataFrame shape: (4992, 2) (2D shapes)
└── Tables
      └── 'table': AnnData (4992, 18085)
with coordinate systems:
    ▸ 'test', with elements:
        test_full_image (Images), test_hires_image (Images), test_lowres_image (Images), test (Shapes)
    ▸ 'test_downscaled_hires', with elements:
        test_hires_image (Images), test (Shapes)
    ▸ 'test_downscaled_lowres', with elements:
        test_lowres_image (Images), test (Shapes)

In [53]:
from spatialdata.transformations import get_transformation

In [54]:
v

SpatialData object
├── Images
│     ├── 'test_full_image': DataTree[cyx] (3, 21571, 19505), (3, 10785, 9752), (3, 5392, 4876), (3, 2696, 2438), (3, 1348, 1219)
│     ├── 'test_hires_image': DataArray[cyx] (3, 2000, 1809)
│     └── 'test_lowres_image': DataArray[cyx] (3, 600, 543)
├── Shapes
│     └── 'test': GeoDataFrame shape: (4992, 2) (2D shapes)
└── Tables
      └── 'table': AnnData (4992, 18085)
with coordinate systems:
    ▸ 'test', with elements:
        test_full_image (Images), test_hires_image (Images), test_lowres_image (Images), test (Shapes)
    ▸ 'test_downscaled_hires', with elements:
        test_hires_image (Images), test (Shapes)
    ▸ 'test_downscaled_lowres', with elements:
        test_lowres_image (Images), test (Shapes)

In [44]:
from napari_spatialdata import Interactive

In [ ]:
Interactive(v)

2025-11-28 18:13:39.647 | WARNING  | napari_spatialdata._viewer:__init__:57 - Due to Shift-L being used as shortcut in napari, it is being deprecated and might not link a new layer to an existing SpatialData object in the viewer. Please use ⌘-L on MacOS or else Ctrl-L.

WARNING: QWindowsWindow::setGeometry: Unable to set geometry 2560x1752+0+34 (frame: 2582x1808-11-11) on QWidgetWindow/"_QtMainWindowClassWindow" on "\\.\DISPLAY1". Resulting geometry: 2560x1494+0+34 (frame: 2582x1550-11-11) margins: 11, 45, 11, 11 minimum size: 554x876 MINMAXINFO maxSize=0,0 maxpos=0,0 mintrack=1130,1808 maxtrack=0,0)
2025-11-28 18:13:46 | [WARNING] QWindowsWindow::setGeometry: Unable to set geometry 2560x1752+0+34 (frame: 2582x1808-11-11) on QWidgetWindow/"_QtMainWindowClassWindow" on "\\.\DISPLAY1". Resulting geometry: 2560x1494+0+34 (frame: 2582x1550-11-11) margins: 11, 45, 11, 11 minimum size: 554x876 MINMAXINFO maxSize=0,0 maxpos=0,0 mintrack=1130,1808 maxtrack=0,0)
2025-11-28 18:13:47.667 | DEBUG    | napari_spatialdata._view:_on_layer_update:569 - Updating layer.
2025-11-28 18:13:47.950 | DEBUG    | napari_spatialdata._view:_on_layer_update:569 - Updating layer.
WARNING: QWindowsWindow::setGeometry: Unable to set geometry 2560x1792+0+34 (frame: 2582x1848-11-11) on QWidgetWindow/"_QtMainWindowClassWindow" on "\\.\DISPLAY1". Resulting geometry: 2560x1494+0+34 (frame: 2582x1550-11-11) margins: 11, 45, 11, 11 minimum size: 554x896 MINMAXINFO maxSize=0,0 maxpos=0,0 mintrack=1130,1848 maxtrack=0,0)
2025-11-28 18:13:48 | [WARNING] QWindowsWindow::setGeometry: Unable to set geometry 2560x1792+0+34 (frame: 2582x1848-11-11) on QWidgetWindow/"_QtMainWindowClassWindow" on "\\.\DISPLAY1". Resulting geometry: 2560x1494+0+34 (frame: 2582x1550-11-11) margins: 11, 45, 11, 11 minimum size: 554x896 MINMAXINFO maxSize=0,0 maxpos=0,0 mintrack=1130,1848 maxtrack=0,0)
WARNING: QWindowsWindow::setGeometry: Unable to set geometry 2560x1808+0+34 (frame: 2582x1864-11-11) on QWidgetWindow/"_QtMainWindowClassWindow" on "\\.\DISPLAY1". Resulting geometry: 2560x1494+0+34 (frame: 2582x1550-11-11) margins: 11, 45, 11, 11 minimum size: 554x904 MINMAXINFO maxSize=0,0 maxpos=0,0 mintrack=1130,1864 maxtrack=0,0)
2025-11-28 18:13:48 | [WARNING] QWindowsWindow::setGeometry: Unable to set geometry 2560x1808+0+34 (frame: 2582x1864-11-11) on QWidgetWindow/"_QtMainWindowClassWindow" on "\\.\DISPLAY1". Resulting geometry: 2560x1494+0+34 (frame: 2582x1550-11-11) margins: 11, 45, 11, 11 minimum size: 554x904 MINMAXINFO maxSize=0,0 maxpos=0,0 mintrack=1130,1864 maxtrack=0,0)
2025-11-28 18:13:53.264 | DEBUG    | napari_spatialdata._view:_on_layer_update:569 - Updating layer.
2025-11-28 18:13:53.269 | DEBUG    | napari_spatialdata._view:_on_layer_update:569 - Updating layer.
2025-11-28 18:13:53.270 | DEBUG    | napari_spatialdata._view:_on_layer_update:569 - Updating layer.
2025-11-28 18:13:56.009 | DEBUG    | napari_spatialdata._view:_on_layer_update:569 - Updating layer.
2025-11-28 18:13:56.012 | DEBUG    | napari_spatialdata._view:_on_layer_update:569 - Updating layer.
2025-11-28 18:13:56.291 | DEBUG    | napari_spatialdata._view:_on_layer_update:569 - Updating layer.

In [47]:
v

SpatialData object
├── Images
│     ├── 'test_hires_image': DataArray[cyx] (3, 2000, 1809)
│     └── 'test_lowres_image': DataArray[cyx] (3, 600, 543)
├── Shapes
│     └── 'test': GeoDataFrame shape: (4992, 2) (2D shapes)
└── Tables
      └── 'table': AnnData (4992, 18085)
with coordinate systems:
    ▸ 'test', with elements:
        test_hires_image (Images), test_lowres_image (Images), test (Shapes)
    ▸ 'test_downscaled_hires', with elements:
        test_hires_image (Images), test (Shapes)
    ▸ 'test_downscaled_lowres', with elements:
        test_lowres_image (Images), test (Shapes)

In [55]:
get_transformation(v['test_hires_image'], 'test')

Scale (y, x)
    [10.78549998 10.78549998]

In [56]:
get_transformation(v['test_lowres_image'], 'test')

Scale (y, x)
    [35.95166687 35.95166687]

In [57]:
35.95166687 / 10.78549998

3.333333358366943

In [58]:
0.092717074 / 0.027815122

3.333333357301111

In [60]:
0.5476 / 0.2781512

1.968713419176333

In [67]:
v['test']['geometry'].get_coordinates().values.max()

np.float64(16873.0)

In [31]:
visium.features.shapes

                               geometry     radius
AACACCTACTATCGAA-1    POINT (4131 4636)  63.917904
AACACGTGCATCGCAC-1  POINT (13355 16640)  63.917904
AACACTTGGCAAGGAA-1   POINT (8845 12067)  63.917904
AACAGGAAGAGCATAG-1  POINT (14716 15518)  63.917904
AACAGGATTCATAGTT-1  POINT (11404 12365)  63.917904
...                                 ...        ...
TGTTGGAACGAGGTCA-1    POINT (8731 9049)  63.917904
TGTTGGAAGCTCGGTA-1    POINT (6598 4776)  63.917904
TGTTGGATGGACTTCT-1   POINT (10447 6653)  63.917904
TGTTGGCCAGACCTAC-1  POINT (11039 12368)  63.917904
TGTTGGCCTACACGTG-1   POINT (3720 10518)  63.917904

[4992 rows x 2 columns]

In [29]:
visium.images.metadata['hires']

{'filename': None,
 'shape': (3, 2000, 1809),
 'axes': 'CYX',
 'OME': {},
 'pixel_size': 1.0,
 'rgb': False}

In [17]:
M_file = r"C:\Users\ge37voy\.cache\InSituPy\demo_datasets\Visium_HE_alignment_files\matrix.csv"
ft = visium.features.transform(
    transformation_matrix=M_file
    )

In [21]:
xenium

InSituData
Method:		Xenium
Slide ID:	0001879
Sample ID:	Replicate 1
Path:		C:\Users\ge37voy\.cache\InSituPy\demo_datasets\xenium_hbreastcancer\output-XETG00000__slide_id__hbreastcancer

    ➤ images
       'nuclei':   (25778, 35416)
    ➤ cells
       MultiCellData with main layer 'main'
           matrix
               AnnData object with n_obs × n_vars = 167780 × 313
               obs: 'transcript_counts', 'control_probe_counts', 'control_codeword_counts', 'total_counts', 'cell_area', 'nucleus_area'
               var: 'gene_ids', 'feature_types', 'genome'
               obsm: 'spatial'
           boundaries
               BoundariesData object with 2 entries:
                   cells
                   nuclei
    ➤ transcripts
       DataFrame with shape Delayed('int-8301f3c0-0854-4c5e-a77d-b042aaccf0fc') x 8

In [20]:
visium.features.shapes

                               geometry     radius
AACACCTACTATCGAA-1    POINT (4131 4636)  63.917904
AACACGTGCATCGCAC-1  POINT (13355 16640)  63.917904
AACACTTGGCAAGGAA-1   POINT (8845 12067)  63.917904
AACAGGAAGAGCATAG-1  POINT (14716 15518)  63.917904
AACAGGATTCATAGTT-1  POINT (11404 12365)  63.917904
...                                 ...        ...
TGTTGGAACGAGGTCA-1    POINT (8731 9049)  63.917904
TGTTGGAAGCTCGGTA-1    POINT (6598 4776)  63.917904
TGTTGGATGGACTTCT-1   POINT (10447 6653)  63.917904
TGTTGGCCAGACCTAC-1  POINT (11039 12368)  63.917904
TGTTGGCCTACACGTG-1   POINT (3720 10518)  63.917904

[4992 rows x 2 columns]

In [22]:
ft.pixel_size

np.float64(2.592434801179086)

In [19]:
ft.shapes

                                       geometry     radius
AACACCTACTATCGAA-1    POINT (282.309 30141.997)  63.917904
AACACGTGCATCGCAC-1   POINT (32685.887 8000.404)  63.917904
AACACTTGGCAAGGAA-1  POINT (20197.666 19013.591)  63.917904
AACAGGAAGAGCATAG-1   POINT (29978.279 4315.518)  63.917904
AACAGGATTCATAGTT-1  POINT (21338.638 12432.899)  63.917904
...                                         ...        ...
TGTTGGAACGAGGTCA-1  POINT (12369.385 18872.743)  63.917904
TGTTGGAAGCTCGGTA-1   POINT (1001.024 23776.617)  63.917904
TGTTGGATGGACTTCT-1   POINT (6415.422 14084.953)  63.917904
TGTTGGCCAGACCTAC-1  POINT (21293.682 13378.101)  63.917904
TGTTGGCCTACACGTG-1   POINT (15447.958 32055.44)  63.917904

[4992 rows x 2 columns]

In [4]:
from spatialdata_io import visium

vp = r"C:\Users\ge37voy\.cache\InSituPy\demo_datasets\visium_hbreastcancer\CytAssist_FFPE_Human_Breast_Cancer"
vis = visium(vp, dataset_id="bc")

c:\Users\ge37voy\AppData\Local\miniconda3\envs\sd313\Lib\site-packages\anndata\_core\anndata.py:1798: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")
c:\Users\ge37voy\AppData\Local\miniconda3\envs\sd313\Lib\site-packages\anndata\_core\anndata.py:1798: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")
c:\Users\ge37voy\AppData\Local\miniconda3\envs\sd313\Lib\site-packages\spatialdata\models\models.py:1183: UserWarning: Converting `region_key: region` to categorical dtype.
  convert_region_column_to_categorical(adata)

In [5]:
vis

SpatialData object
├── Images
│     ├── 'bc_hires_image': DataArray[cyx] (3, 2000, 1809)
│     └── 'bc_lowres_image': DataArray[cyx] (3, 600, 543)
├── Shapes
│     └── 'bc': GeoDataFrame shape: (4992, 2) (2D shapes)
└── Tables
      └── 'table': AnnData (4992, 18085)
with coordinate systems:
    ▸ 'bc', with elements:
        bc_hires_image (Images), bc_lowres_image (Images), bc (Shapes)
    ▸ 'bc_downscaled_hires', with elements:
        bc_hires_image (Images), bc (Shapes)
    ▸ 'bc_downscaled_lowres', with elements:
        bc_lowres_image (Images), bc (Shapes)

In [6]:
from insitupy.spatialdata.convert import convert_from_spatialdata

In [7]:
dataset_id = "bc"
sample_id = "test_id"
# Convert to InSituData format
data = convert_from_spatialdata(
    sdata=vis,
    image_keys={
        "hires": f"{dataset_id}_hires_image",
        "lowres": f"{dataset_id}_lowres_image"
    },
    features_key=dataset_id,
    cells_key=None,  # No cells available in Visium data
    table_key="table",
    cell_boundaries_key=None,  # Visium uses spots, not boundaries
    nucleus_boundaries_key=None,
    transcripts_key=None,  # Visium doesn't have single-molecule transcripts
    slide_id=dataset_id if dataset_id else "visium_slide",
    sample_id=sample_id if sample_id else "visium_sample",
    method_name="Visium",
)

INFO: Using 'bc' coordinate system for pixel size extraction.

Extracted pixel size 1.0 from 'bc'
Adding images...

WARNING: Indices in `.shapes` do not match `.data.obs_names`. Shapes will be renamed according to the `obs_names`. For this to be valid, please make sure that the order of elements in `.shapes` and `.data` matches.

In [8]:
data

InSituData
Method:		Visium
Slide ID:	bc
Sample ID:	test_id
Path:		None

    ➤ images
       'hires':    (3, 2000, 1809)
       'lowres':   (3, 600, 543)
    ➤ features
       FeatureData (Type: 'feature')
           .data: 4992 obs × 18085 vars
           .shapes: 4992 geometries

In [9]:
from insitupy import CACHE

In [10]:
feature_path = CACHE / "out" / "features_test"
data.saveas(feature_path, overwrite=True)

Saving data to C:\Users\ge37voy\.cache\InSituPy\out\features_test

... storing 'feature_types' as categorical
... storing 'genome' as categorical

Saved.

In [13]:
from insitupy import InSituData

In [14]:
vr = InSituData.read(feature_path)

In [16]:
vr.load_all()

In [17]:
vr

InSituData
Method:		Visium
Slide ID:	bc
Sample ID:	test_id
Path:		C:\Users\ge37voy\.cache\InSituPy\out\features_test

    ➤ images
       'hires':    (3, 2000, 1809)
       'lowres':   (3, 600, 543)
    ➤ features
       FeatureData (Type: 'feature')
           .data: 4992 obs × 18085 vars
           .shapes: 4992 geometries

In [20]:
for elem_type, key, elem in vis.gen_elements():
    print(key)

bc_hires_image
bc_lowres_image
bc
table

In [ ]:
xdconv = convert_from_spatialdata(
    sdata=sdata,
    image_keys={
        "nuclei": "morphology_mip",
        "mip": "morphology_focus"
    },
    cells_key="cell_circles",
    table_key="table",
    cell_boundaries_key="cell_labels",
    nucleus_boundaries_key="nucleus_labels",
    transcripts_key="transcripts",
    slide_id="slide_test",
    sample_id="sample_test",
    method_name="Xenium"
)