# Working with histological annotations and regions

In [1]:
## The following code ensures that all functions and init files are reloaded before executions.
%load_ext autoreload
%autoreload 2

In [2]:
from pathlib import Path

from insitupy import CACHE, InSituData

## Load Xenium data into `InSituData` object

Now the Xenium data can be parsed by providing the data path to the `InSituPy` project folder

In [3]:
insitupy_project = Path(CACHE / "out/demo_insitupy_project")
xd = InSituData.read(insitupy_project)

In [4]:
xd

InSituData
Method:		Xenium
Slide ID:	0001879
Sample ID:	Replicate 1
UID:		None
Path:		C:\Users\ge37voy\.cache\InSituPy\out\demo_insitupy_project

    ➤ images
       'CD20':     (25778, 35416)
       'HE':       (25778, 35416, 3)
       'HER2':     (25778, 35416)
       'nuclei':   (25778, 35416)
    ➤ cells
       MultiCellData with main layer 'main'
           table
               AnnData object with n_obs × n_vars = 157600 × 297
               obs: 'transcript_counts', 'control_probe_counts', 'control_codeword_counts', 'total_counts', 'cell_area', 'nucleus_area', 'n_genes_by_counts', 'n_genes', 'leiden'
               var: 'gene_ids', 'feature_types', 'genome', 'n_cells_by_counts', 'mean_counts', 'pct_dropout_by_counts', 'total_counts', 'n_cells'
               uns: 'insitupy', 'leiden', 'leiden_colors', 'log1p', 'neighbors', 'pca', 'umap'
               obsm: 'X_pca', 'X_umap', 'spatial'
               varm: 'PCs'
               layers: 'counts', 'norm_counts'
               obsp: 'connectivities', 'distances'
           boundaries
               BoundariesData object with 2 entries:
                   cells
                   nuclei
    ➤ transcripts
       DataFrame with shape <dask_expr.expr.Scalar: expr=ReadParquetFSSpec(5597954).size() // 8, dtype=int64> x 8

## Histological information in InSituPy

InSituPy organizes histological information into two categories: **Annotations** and **Regions**.

<left><img src="../../_static/img/geometries_overview.png" class="center" width="600"/></left>

### Annotations

Annotations are user-defined geometries (polygons, points, or lines) that mark biological features:

- **Class**: The biological category (e.g., "tumor", "immune cells", "stroma")
- **Key**: The annotation source (e.g., pathologist name, annotation batch)
- **ID**: Unique identifier to distinguish individual annotations

Classes within a key need not be unique, but multiple annotations can share the same class label.

### Regions

Regions are polygons that define spatial areas within a dataset:

- **Key**: Groups related regions (e.g., "TMA", "tissue_sections")
- **Name**: Unique identifier within each key (e.g., "TMA_A1", "TMA_A2")

**Common use cases:**
- TMA cores
- Multiple tissue sections on one slide
- Regions of interest for focused analysis

### Adding histological information

This notebook demonstrates two workflows to add histological annotations:

1. **Interactive annotation** using InSituPy's napari viewer integration
2. **Import annotations** from QuPath

### 1. In `napari` viewer

First visualize the Xenium data using `.show()`.

In [5]:
xd.show()

2026-10-06 15:42:36 | [INFO] No OpenGL_accelerate module loaded: No module named 'OpenGL_accelerate'
WARNING: QWindowsWindow::setGeometry: Unable to set geometry 1626x980-532+723 (frame: 1648x1036-543+678) on QWidgetWindow/"_QtMainWindowClassWindow" on "\\.\DISPLAY1". Resulting geometry: 2441x1473-529+737 (frame: 2463x1529-540+692) margins: 11, 45, 11, 11 minimum size: 283x506 MINMAXINFO maxSize=0,0 maxpos=0,0 mintrack=447,815 maxtrack=0,0)
2026-10-06 15:42:38 | [WARNING] QWindowsWindow::setGeometry: Unable to set geometry 1626x980-532+723 (frame: 1648x1036-543+678) on QWidgetWindow/"_QtMainWindowClassWindow" on "\\.\DISPLAY1". Resulting geometry: 2441x1473-529+737 (frame: 2463x1529-540+692) margins: 11, 45, 11, 11 minimum size: 283x506 MINMAXINFO maxSize=0,0 maxpos=0,0 mintrack=447,815 maxtrack=0,0)

2026-10-06 15:42:45 | [INFO] Extracting unique gene names from Dask DataFrame...
2026-10-06 15:42:47 | [INFO] Found 541 unique genes

INFO: Added 4 new annotations to key 'test'
INFO: Added 6 new annotations to existing key 'test'

Annotations and regions are added with the **Geometries** tab on the right side of the viewer:

<img src="../../demo_data/demo_screenshots/geometries_widget.jpg" class="center" width="300"/>

- **Type**: `Annotations` for histological annotations (e.g. tumor, immune cells) or `Regions` for larger areas such as TMA cores or tissue sections.
- **Key**: the group the geometries belong to, e.g. the annotator or the annotation batch. Pick an existing key or type a new one.
- **Name**: restricts **Show** to one class or region of the key (`(all)` loads everything).
- **Show**: loads the geometries of the selected type and key from the `InSituData` object into the viewer.
- **Add shapes** / **Add points**: create a new, empty layer for drawing. You are asked for the key. Points are available for annotations only.
- **Open Features Table**: opens napari's features table for the active layer, where the `name` of each geometry can be edited.

InSituPy recognises the layer type by a symbol in the layer name: `🔬 <key>` for shape annotations, `📍 <key>` for point annotations and `🌍 <key>` for regions. Always create layers with this tab and not with the normal `napari` layer menu.

To add annotations:

1. Select the **Type**, click **Add shapes** (or **Add points**) and enter a key, e.g. `TestKey`.
2. Draw shapes or place points with the tools on the top left of napari.
3. Give each geometry its `name` in the Features Table. For annotations the name is the **class** (e.g. "tumor"), and several geometries may share it. For regions the name has to be unique within the key; new regions are numbered "Region 1", "Region 2", ... automatically.
4. Click **Refresh** to update labels and colors, then **Sync** to store the geometries in the `InSituData` object. Sync also removes geometries that were deleted in the viewer, and it aborts with a warning if a region key contains duplicate names.

In [8]:
# Instead of the "Sync" button, the geometries can also be synchronized from code:
# from insitupy.interactive import sync_geometries
# sync_geometries()

In [9]:
xd

InSituData
Method:		Xenium
Slide ID:	0001879
Sample ID:	Replicate 1
Path:		C:\Users\ge37voy\.cache\InSituPy\out\demo_insitupy_project

    ➤ images
       'CD20':     (25778, 35416)
       'HE':       (25778, 35416, 3)
       'HER2':     (25778, 35416)
       'nuclei':   (25778, 35416)
    ➤ cells
       MultiCellData with main layer 'main'
           table
               AnnData object with n_obs × n_vars = 157600 × 297
               obs: 'transcript_counts', 'control_probe_counts', 'control_codeword_counts', 'total_counts', 'cell_area', 'nucleus_area', 'n_genes_by_counts', 'n_genes', 'leiden'
               var: 'gene_ids', 'feature_types', 'genome', 'n_cells_by_counts', 'mean_counts', 'pct_dropout_by_counts', 'total_counts', 'n_cells'
               uns: 'leiden', 'leiden_colors', 'log1p', 'neighbors', 'pca', 'umap'
               obsm: 'X_pca', 'X_umap', 'spatial'
               varm: 'PCs'
               layers: 'counts', 'norm_counts'
               obsp: 'connectivities', 'distances'
           boundaries
               BoundariesData object with 2 entries:
                   cells
                   nuclei
    ➤ annotations
       TestKey:	9 annotations, 2 classes ('TestClass', 'points')

In [7]:
xd.annotations["test"]

,objectType,geometry,name,color,origin,layer_type,size
id,,,,,,,
dbcfcbca-d902-4066-b1fd-59a7ecbe833e,annotation,"POLYGON ((1714.80713 2296.69531, 1629.53015 24...",a,"[12, 113, 255]",manual,Shapes,NaN
871f8def-e97c-4c43-b383-a60daf1652f4,annotation,"POLYGON ((3287.69556 2817.83301, 2975.01294 30...",a,"[12, 113, 255]",manual,Shapes,NaN
f9980183-b66d-4009-8110-e37f8dcb33a1,annotation,"POLYGON ((4756.35645 2258.79443, 4652.12891 24...",b,"[202, 40, 0]",manual,Shapes,NaN
38b89a84-cd20-470f-8554-413094c13da0,annotation,"POLYGON ((3543.52686 1567.10254, 3477.2002 173...",d,"[255, 40, 186]",manual,Shapes,NaN
d3d36167-4e20-4b3a-a67e-4a77f6970d0d,annotation,POINT (1155.76855 998.58867),,"[128, 128, 128]",manual,Points,10.0
161ad18b-26a3-43bc-b84e-c4ef4c29ff58,annotation,POINT (2131.71734 1188.09329),,"[128, 128, 128]",manual,Points,10.0
6d85236b-e0c9-443e-a1e6-6b7145ceb1bd,annotation,POINT (3249.79461 1443.92453),,"[128, 128, 128]",manual,Points,10.0
9644df4e-2742-4abb-93bf-070f6079cd57,annotation,POINT (3590.90293 1121.76667),,"[128, 128, 128]",manual,Points,10.0
37ad0986-88d8-4c04-87c3-78056e5ceca3,annotation,POINT (4491.04988 1358.64745),,"[128, 128, 128]",manual,Points,10.0
ae2dab5c-7571-4c1c-aa30-1b7b04c3ff12,annotation,POINT (5239.59313 2040.86408),,"[128, 128, 128]",manual,Points,10.0

#### Export annotations or regions

To export annotations or regions, one can save the `AnnotationsData` or `RegionsData` object as `.geojson` file.

In [8]:
xd.annotations.save(path=CACHE / "out/annotations_export", overwrite=True)

### 2. Create annotations in QuPath

To create annotations in QuPath, follow these steps:

1. Export the registered HE image as OME-TIFF by setting `as_zarr=False`:

In [9]:
xd.images.save(CACHE / "out/image_export", keys_to_save="HE", as_zarr=False, overwrite=True)

2. Open the exported image in QuPath and start with the annotations. Documentations on QuPath can be found [here](https://qupath.readthedocs.io/en/stable/index.html).

3. Select an annotation tool from the bar on the top left:

<img src="../../demo_data/demo_screenshots/qupath_annotation_buttons.jpg" class="center" width="300"/>

4. Add as many annotations as you want and label them by setting classes in the annotation list. Do not forget to press the "Set class" button:

<img src="../../demo_data/demo_screenshots/qupath_annotation_list.jpg" class="center" width="350"/>

5. Export annotations using `File > Export objects as GeoJSON`. Tick `Pretty JSON` to get an easily readable JSON file. The file name needs to have following structure: `annotation-{slide_id}__{sample_id}__{annotation_label}`.

### Import annotations into `InSituData`

For demonstration purposes, we created dummy annotation files in `./demo_annotations/`. To add the annotations to `InSituData` follow the steps below.

### 3. Create regions in QuPath

For creating regions, one can use the same annotation tools as described above. But instead of setting a class for the annotation, you can name the region by double-clicking on it, and selecting "Set Properties":

<img src="../../demo_data/demo_screenshots/set_properties.jpg" class="center" width="350"/>

For export, regions can then be selected and exported in the same way as described above for annotations.

## Import annotations and regions

Since annotations could have been done on images with different resolutions, it is important to specify the `pixel_size` during the import. In standard Xenium experiments the pixel size is 0.2125 µm but if the images were downscaled before the annotation, this value might differ.

In `QuPath` the pixel size and other image metadata can be looked up under "Image" and "Pixel width" or "Pixel height":

<img src="../../demo_data/demo_screenshots/qupath_properties_window.jpg" class="center" width="350"/>

In [10]:
xd.import_annotations(
    files=[
        "../../demo_data/demo_annotations/annotations-0001879__Replicate 1__demo.geojson",
        "../../demo_data/demo_annotations/annotations-0001879__Replicate 1__demo2.geojson",
        "../../demo_data/demo_annotations/annotations-mixed_types.geojson"
           ],
    keys=["demo", "demo2", "demo3"],
    scale_factor=0.2125
    )

In [11]:
xd.annotations["demo"]

,objectType,geometry,name,color,scale,origin,layer_type
id,,,,,,,
bd3aacca-1716-4df8-91dd-bf8f6413a7bd,annotation,"POLYGON ((1883.3875 2297.975, 1883.3875 2300.1...",Positive,"[250, 62, 62]","(1, 1)",file,Shapes
69814505-4059-42cd-8df2-752f7eb0810d,annotation,"POLYGON ((2782.9 2654.55, 2777.885 2655.0175, ...",Positive,"[250, 62, 62]","(1, 1)",file,Shapes
1957cd32-0a21-4b45-9dae-ecf236217140,annotation,"POLYGON ((6582.24275 4874.325, 6583.675 4874.3...",Negative,"[112, 112, 225]","(1, 1)",file,Shapes
19d2197a-1b8e-456f-8223-fba74641ac1c,annotation,"POLYGON ((6622.5625 3486.7, 6619.1625 3487.125...",Negative,"[112, 112, 225]","(1, 1)",file,Shapes

In [12]:
xd.annotations["demo2"]

,objectType,geometry,name,color,scale,origin,layer_type
id,,,,,,,
1970eccb-ad38-4b4b-b7a8-54509027b57d,annotation,"POLYGON ((5380.2875 827.05, 5379.0125 827.475,...",Negative,"[112, 112, 225]","(1, 1)",file,Shapes
a3b32cce-1bb9-4a6f-b1d1-9e0c44420cfa,annotation,"POLYGON ((6576.875 2306.6875, 6575.6 2307.1125...",Positive,"[250, 62, 62]","(1, 1)",file,Shapes
92bfe928-a21f-4864-b7cb-f0d300113d88,annotation,"MULTIPOLYGON (((4575.975 4152.4625, 4575.975 4...",Other,"[255, 200, 0]","(1, 1)",file,Shapes
a6c17a54-6839-40b2-8531-c9227635f344,annotation,"POLYGON ((1381.4625 3639.275, 1380.1875 3639.7...",Other,"[255, 200, 0]","(1, 1)",file,Shapes
e78efe2f-d185-4ab6-9cc9-6621897f3662,annotation,"POLYGON ((6272.92138 3936.1375, 6263.65 3945.2...",Negative,"[112, 112, 225]","(1, 1)",file,Shapes

In [13]:
xd.annotations["demo3"]

,objectType,geometry,name,color,scale,origin,layer_type
id,,,,,,,
8f57c3c3-2216-48b7-99bd-aba12d8c3c41,annotation,"POLYGON ((3828.4 2261.74375, 3827.8135 2274.22...",Stroma,"[150, 200, 150]","(1, 1)",file,Shapes
7e8f8db4-81d4-472e-8e93-0fc756df87aa,annotation,"POLYGON ((2618.425 1436.075, 2618.07225 1436.1...",Stroma,"[150, 200, 150]","(1, 1)",file,Shapes
38a48ddb-f33c-4c61-b996-330b25d84081,annotation,"LINESTRING (3600.5575 1648.7535, 3878.03575 13...",Necrosis,"[50, 50, 50]","(1, 1)",file,Shapes
eee244c9-e919-41ae-bb91-44c7abcc0cec,annotation,"LINESTRING (2483.6235 1334.39588, 2855.93412 1...",Immune cells,"[160, 90, 160]","(1, 1)",file,Shapes
e3d4c0b6-0998-4692-ab7d-f580f713e275,annotation,POINT (5096.23663 1632.56312),unclassified,"[0, 0, 0]","(1, 1)",file,Points
e9105240-3b35-489e-994f-e8f9c4786516,annotation,"MULTIPOINT ((4219.655 1650.71912), (4261.94675...",Stroma,"[150, 200, 150]","(1, 1)",file,Points
2802df97-78ad-44ac-8e6b-d9b9406c8e3f,annotation,"MULTIPOINT ((3372.7915 2005.41562), (3530.0415...",Tumor,"[200, 0, 0]","(1, 1)",file,Points

## Load regions

Regions can be created in QuPath either as described above or using tools like the TMA dearrayer. They are also exported as objects as annotations but different to annotations they do not have a classification and each name of a region has to be unique.

In the following demo regions are read. One of the region files has non-unique names to demonstrate the warning that appears in this case.

### In regions classes have to be unique

When reading an "Annotation" `.geojson` as shown below, the `import_regions` function throws an error indicating that in regions only one geometry per class is allowed. Further, only normal polygons (`shapely.Polygon`-typed) are allowed. Any other types of geometries (Points, Lines, MultiPolygons, ...) are skipped.

In [14]:
xd.import_regions(
    files=[
        "../../demo_data/demo_annotations/annotations-mixed_types.geojson"
        ],
    keys=['test'],
    scale_factor=0.2125
    )

C:\Users\ge37voy\Github\insitupy\insitupy\containers\shapes_data.py:321: UserWarning: The names of the regions for key 'test' were not unique and thus the key was skipped. In regions only one geometry per class is allowed.To achieve this in the napari viewer select one layer per region and give each layer a unique name.
  is_unique = self._check_uniqueness(dataframe=annot_df, key=key, verbose=False)

Multiple regions can be imported simultaneously.

In [15]:
xd.import_regions(
    files=[
        "../../demo_data/demo_regions/regions-0001879__Replicate 1__demo_regions.geojson",
        "../../demo_data/demo_regions/regions-0001879__Replicate 1__TMA.geojson",
        ],
    keys=['demo_regions', 'TMA'],
    scale_factor=0.2125
    )

C:\Users\ge37voy\Github\insitupy\insitupy\_core\data.py:1494: UserWarning: No 'color' column found in the imported data. Setting all colors to red.
  self._regions.add_data(data=file,
C:\Users\ge37voy\Github\insitupy\insitupy\_core\data.py:1494: UserWarning: No 'color' column found in the imported data. Setting all colors to red.
  self._regions.add_data(data=file,

Properties of the `anotations` and `regions` modalities can be inspected in the InSituData representation:

In [16]:
xd

InSituData
Method:		Xenium
Slide ID:	0001879
Sample ID:	Replicate 1
UID:		None
Path:		C:\Users\ge37voy\.cache\InSituPy\out\demo_insitupy_project

    ➤ images
       'CD20':     (25778, 35416)
       'HE':       (25778, 35416, 3)
       'HER2':     (25778, 35416)
       'nuclei':   (25778, 35416)
    ➤ cells
       MultiCellData with main layer 'main'
           table
               AnnData object with n_obs × n_vars = 157600 × 297
               obs: 'transcript_counts', 'control_probe_counts', 'control_codeword_counts', 'total_counts', 'cell_area', 'nucleus_area', 'n_genes_by_counts', 'n_genes', 'leiden'
               var: 'gene_ids', 'feature_types', 'genome', 'n_cells_by_counts', 'mean_counts', 'pct_dropout_by_counts', 'total_counts', 'n_cells'
               uns: 'insitupy', 'leiden', 'leiden_colors', 'log1p', 'neighbors', 'pca', 'umap'
               obsm: 'X_pca', 'X_umap', 'spatial'
               varm: 'PCs'
               layers: 'counts', 'norm_counts'
               obsp: 'connectivities', 'distances'
           boundaries
               BoundariesData object with 2 entries:
                   cells
                   nuclei
    ➤ annotations
       test:	10 annotations, 4 names ('', 'a', 'b', 'd')
       demo:	4 annotations, 2 names ('Negative', 'Positive')
       demo2:	5 annotations, 3 names ('Negative', 'Other', 'Positive')
       demo3:	7 annotations, 5 names ('Immune cells', 'Necrosis', 'Stroma', 'Tumor', 'unclassified')
    ➤ regions
       region key:	4 regions, 4 names ('Region 1', 'Region 2', 'Region 3', 'Region 4')
       demo_regions:	3 regions, 3 names ('Region1', 'Region2', 'Region3')
       TMA:	6 regions, 6 names ('A-1', 'A-2', 'A-3', 'B-1', 'B-2', 'B-3')
    ➤ transcripts
       DataFrame with shape <dask_expr.expr.Scalar: expr=ReadParquetFSSpec(5597954).size() // 8, dtype=int64> x 8

## Visualization of `annotations` and `regions` using `napari` viewer

Annotations and regions stored in the `InSituData` object are shown with the same **Geometries** tab described above: select the **Type** and the **Key** and click **Show**. Use **Name** to load only one class or region of that key. The geometries appear as layers named after their symbol and key (e.g. `🔬 demo2`, `🌍 TMA`) and are labelled with their `name`.

In [17]:
xd.show()

WARNING: QWindowsWindow::setGeometry: Unable to set geometry 1626x980-532+723 (frame: 1648x1036-543+678) on QWidgetWindow/"_QtMainWindowClassWindow" on "\\.\DISPLAY1". Resulting geometry: 2441x1473-529+737 (frame: 2463x1529-540+692) margins: 11, 45, 11, 11 minimum size: 283x506 MINMAXINFO maxSize=0,0 maxpos=0,0 mintrack=447,815 maxtrack=0,0)
2026-10-06 16:44:40 | [WARNING] QWindowsWindow::setGeometry: Unable to set geometry 1626x980-532+723 (frame: 1648x1036-543+678) on QWidgetWindow/"_QtMainWindowClassWindow" on "\\.\DISPLAY1". Resulting geometry: 2441x1473-529+737 (frame: 2463x1529-540+692) margins: 11, 45, 11, 11 minimum size: 283x506 MINMAXINFO maxSize=0,0 maxpos=0,0 mintrack=447,815 maxtrack=0,0)

2026-10-06 16:44:48 | [INFO] Extracting unique gene names from Dask DataFrame...
2026-10-06 16:44:51 | [INFO] Found 541 unique genes

### Assign annotations to observations

To use the annotations in analyses (e.g. to select only observations within a certain annotation or compare gene expression between different annotations) one can use the `assign_annotations` function. By default it stores one categorical column per annotation key in `xd.cells.table.obsm['annotations']`; cells that lie outside every annotation of a given key get the label `'unassigned'`. Pass `add_to_obs=True` to instead add an `annotations-{key}` column to `xd.cells.table.obs`.

In [18]:
xd.assign_annotations(overwrite=True)

2026-10-06 16:45:39 | [INFO] Using CellData from MultiCellData layer 'main'.
2026-10-06 16:45:39 | [INFO] Assigning key 'test'...

100%|██████████| 4/4 [00:00<00:00,  8.58it/s]

2026-10-06 16:45:47 | [INFO] Added results to `.cells['main'].table.obsm['annotations']`
2026-10-06 16:45:47 | [INFO] Assigning key 'demo'...

100%|██████████| 2/2 [00:00<00:00,  8.18it/s]

2026-10-06 16:45:55 | [INFO] Added results to `.cells['main'].table.obsm['annotations']`
2026-10-06 16:45:55 | [INFO] Assigning key 'demo2'...

100%|██████████| 3/3 [00:00<00:00, 10.83it/s]

2026-10-06 16:46:03 | [INFO] Added results to `.cells['main'].table.obsm['annotations']`
2026-10-06 16:46:03 | [INFO] Assigning key 'demo3'...

100%|██████████| 5/5 [00:00<00:00, 18.88it/s]

2026-10-06 16:46:11 | [INFO] Added results to `.cells['main'].table.obsm['annotations']`

In [19]:
xd.assign_regions()

2026-10-06 16:46:12 | [INFO] Using CellData from MultiCellData layer 'main'.
2026-10-06 16:46:12 | [INFO] Assigning key 'region key'...

100%|██████████| 4/4 [00:00<00:00, 19.48it/s]

2026-10-06 16:46:20 | [INFO] Added results to `.cells['main'].table.obsm['regions']`
2026-10-06 16:46:20 | [INFO] Assigning key 'demo_regions'...

100%|██████████| 3/3 [00:00<00:00, 20.04it/s]

2026-10-06 16:46:28 | [INFO] Added results to `.cells['main'].table.obsm['regions']`
2026-10-06 16:46:28 | [INFO] Assigning key 'TMA'...

100%|██████████| 6/6 [00:00<00:00, 19.01it/s]

2026-10-06 16:46:35 | [INFO] Added results to `.cells['main'].table.obsm['regions']`

In [20]:
xd

InSituData
Method:		Xenium
Slide ID:	0001879
Sample ID:	Replicate 1
UID:		None
Path:		C:\Users\ge37voy\.cache\InSituPy\out\demo_insitupy_project

    ➤ images
       'CD20':     (25778, 35416)
       'HE':       (25778, 35416, 3)
       'HER2':     (25778, 35416)
       'nuclei':   (25778, 35416)
    ➤ cells
       MultiCellData with main layer 'main'
           table
               AnnData object with n_obs × n_vars = 157600 × 297
               obs: 'transcript_counts', 'control_probe_counts', 'control_codeword_counts', 'total_counts', 'cell_area', 'nucleus_area', 'n_genes_by_counts', 'n_genes', 'leiden'
               var: 'gene_ids', 'feature_types', 'genome', 'n_cells_by_counts', 'mean_counts', 'pct_dropout_by_counts', 'total_counts', 'n_cells'
               uns: 'insitupy', 'leiden', 'leiden_colors', 'log1p', 'neighbors', 'pca', 'umap'
               obsm: 'X_pca', 'X_umap', 'spatial', 'annotations', 'regions'
               varm: 'PCs'
               layers: 'counts', 'norm_counts'
               obsp: 'connectivities', 'distances'
           boundaries
               BoundariesData object with 2 entries:
                   cells
                   nuclei
    ➤ annotations
       test:	10 annotations, 4 names ('', 'a', 'b', 'd')
       demo:	4 annotations, 2 names ('Negative', 'Positive')
       demo2:	5 annotations, 3 names ('Negative', 'Other', 'Positive')
       demo3:	7 annotations, 5 names ('Immune cells', 'Necrosis', 'Stroma', 'Tumor', 'unclassified')
    ➤ regions
       region key:	4 regions, 4 names ('Region 1', 'Region 2', 'Region 3', 'Region 4')
       demo_regions:	3 regions, 3 names ('Region1', 'Region2', 'Region3')
       TMA:	6 regions, 6 names ('A-1', 'A-2', 'A-3', 'B-1', 'B-2', 'B-3')
    ➤ transcripts
       DataFrame with shape <dask_expr.expr.Scalar: expr=ReadParquetFSSpec(5597954).size() // 8, dtype=int64> x 8

After assigning the annotations, the already analyzed labels analyzed are marked with a ✔:

In [21]:
xd.regions["demo_regions"]

,objectType,name,geometry,origin,color,layer_type
id,,,,,,
2d0da635-c408-459f-9178-839097fe5a98,annotation,Region1,"POLYGON ((1564.425 1321.9625, 2267.8 1321.9625...",file,"[255, 0, 0]",Shapes
ce6c2342-620d-4f44-be03-68a4454e9b33,annotation,Region2,"POLYGON ((4541.7625 1356.3875, 5613.825 1356.3...",file,"[255, 0, 0]",Shapes
70a125ec-c53e-469b-8927-efe224e504c1,annotation,Region3,"POLYGON ((2110.7625 2708.3125, 3387.675 2708.3...",file,"[255, 0, 0]",Shapes

Following cells show examples how to explore the assigned annotations:

In [22]:
xd.cells.table.obsm['annotations']['demo2']

2         unassigned
5         unassigned
8         unassigned
10        unassigned
13        unassigned
             ...
167776    unassigned
167777    unassigned
167778    unassigned
167779    unassigned
167780    unassigned
Name: demo2, Length: 157600, dtype: object

In [23]:
# print number of cells within each annotation
annots = xd.cells.table.obsm['annotations']['demo2']
annots.value_counts()

demo2
unassigned    148458
Negative        4839
Other           2605
Positive        1698
Name: count, dtype: int64

In [24]:
# print number of cells within each annotation
annots = xd.cells.table.obsm['annotations']['demo2']
annots.value_counts()

demo2
unassigned    148458
Negative        4839
Other           2605
Positive        1698
Name: count, dtype: int64

In [25]:
# show geopandas dataframe for one annotation
xd.annotations["demo2"]

,objectType,geometry,name,color,scale,origin,layer_type
id,,,,,,,
1970eccb-ad38-4b4b-b7a8-54509027b57d,annotation,"POLYGON ((5380.2875 827.05, 5379.0125 827.475,...",Negative,"[112, 112, 225]","(1, 1)",file,Shapes
a3b32cce-1bb9-4a6f-b1d1-9e0c44420cfa,annotation,"POLYGON ((6576.875 2306.6875, 6575.6 2307.1125...",Positive,"[250, 62, 62]","(1, 1)",file,Shapes
92bfe928-a21f-4864-b7cb-f0d300113d88,annotation,"MULTIPOLYGON (((4575.975 4152.4625, 4575.975 4...",Other,"[255, 200, 0]","(1, 1)",file,Shapes
a6c17a54-6839-40b2-8531-c9227635f344,annotation,"POLYGON ((1381.4625 3639.275, 1380.1875 3639.7...",Other,"[255, 200, 0]","(1, 1)",file,Shapes
e78efe2f-d185-4ab6-9cc9-6621897f3662,annotation,"POLYGON ((6272.92138 3936.1375, 6263.65 3945.2...",Negative,"[112, 112, 225]","(1, 1)",file,Shapes

## Save imported annotations in `InSituPy` project

In [27]:
xd.save()

2026-10-06 16:53:44 | [INFO] Saving to existing path: C:\Users\ge37voy\.cache\InSituPy\out\demo_insitupy_project
2026-10-06 16:53:44 | [INFO] Updating project in C:\Users\ge37voy\.cache\InSituPy\out\demo_insitupy_project
2026-10-06 16:53:44 | [INFO] Updating cells...
2026-10-06 16:54:26 | [INFO] Updating annotations...
2026-10-06 16:54:26 | [INFO] Updating regions...
2026-10-06 16:54:26 | [INFO] Saved.